framework:
    default_locale: '%env(DEFAULT_LOCALE)%'
    enabled_locales: '%enabled_locales%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%env(DEFAULT_LOCALE)%'
        providers:
